config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:edit, :update, :show]
  root 'items#index'
    resources :address, only: [:create,:edit, :update]
  
    resources :card, only: [:new, :show] do
      collection do
        post 'show', to: 'card#show'
        post 'pay', to: 'card#pay'
        post 'delete', to: 'card#delete'
      end
    end

    resources :items  do
      resources :purchase, only: [:index] do
        collection do
          get 'index', to: 'purchase#index'
          post 'pay', to: 'purchase#pay'
          get 'done', to: 'purchase#done'
        end
      end
      collection do
        get :search
        get :search_two
        get :items_search
      end
    end
  resources :categories, only: [:new, :show]
end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  require 'payjp'
  before_action :set_item
  before_action :set_card, only: [:index, :pay]

  def index
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
    if @card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def done
  end

  def pay
    @item.update(saler_id: current_user.id)
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    :amount => @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    :customer => @card.customer_id, #顧客ID
    :currency => 'jpy', #日本円
  )
  redirect_to action: 'done' #完了画面に移動
  end

  private 

  def set_item
    @item =  Item.find(params[:item_id])
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end


end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/purchase/done.html.haml
.purchase-content
  -# 商品購入の完了
  .purchase-item
    .purchase-item__title
      購入が完了しました！
    -# トップページへのボタン
    .purchase-item__top
      =link_to "トップページ", root_path, class: "purchase-item__top__link"

app/views/purchase/index.html.haml
.main1
  .main1__section
    -# 購入内容の確認
    %h2.buy-head 購入内容の確認
    .main1__section__inner
      .main1__section__inner__items
        .item-box
          %h3.item_image
            =image_tag @item.images[0].image.url
          .item-box-data
            %p.item-name 
              = @item.name
            %p.item-price 
              %span.money 
                = @item.price
              %span.tax 円(税込)送料込み
              
    .main1__section__inner
      -# 商品画像と名前
      .main1__section__inner__items
        = form_with model: @item do |f|
          -# 支払い金額 ~円
          %ul.price-table
            %li.price-big
              .merge-price
                %span 支払い金額
              .buy-price
                %span
                  = @item.price
          .item-info
            .item-info-inner
              %h3 支払い方法
              - if @default_card_information.blank?
                %br 
                .links
                =icon("fas","star")
                =link_to "登録してください", new_card_path
              - else
                -#以下カード情報を表示
                = "**** **** **** " + @default_card_information.last4
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
              -# カード情報を登録しているか、どうかでビューが変わる
          -# .item-info
          -#   .item-info-inner
          -#     %h3 配送先
          -#     -# 同じく住所を登録しているかどうかでビューが変わる
          -#     .links
          -#       =icon("fas","star")
          -#       =link_to "登録してください","#"
          .item-info
            -# 購入ボタン
            .item-info-button
              = form_tag(action: :pay, method: :post) do
                -# %button 購入する
              = form_tag(action: :pay, method: :post) do
                %button 購入する