config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:edit, :update, :show]
  root 'items#index'
    resources :address, only: [:create,:edit, :update]
  
    resources :card, only: [:new, :show] do
      collection do
        post 'show', to: 'card#show'
        post 'pay', to: 'card#pay'
        post 'delete', to: 'card#delete'
      end
    end

    resources :items  do
      resources :purchase, only: [:index] do
        collection do
          get 'index', to: 'purchase#index'
          post 'pay', to: 'purchase#pay'
          get 'done', to: 'purchase#done'
        end
      end
      collection do
        get :search
        get :search_two
        get :items_search
      end
    end
  resources :categories, only: [:new, :show]
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  
  belongs_to :category
  belongs_to :user

  validates :name, presence: true, length: {maximum: 40}
  validates :description, presence: true, length: {maximum: 1000}
  validates :price, length: {maximum: 10}
  validates :prefecture_id, presence: true, numericality: { less_than_or_equal_to: 47 }
  validates :category_id, presence: true
  validates :child_category_id, presence: true
  validates :grandchild_category_id, presence: true, :numericality => { :greater_than_or_equal_to => 1} 
  
  #アソシエーションを組んであるモデルに対してのバリデーションを組む
  validates_associated :images
  validates :images, presence: true
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture


  enum delivery_charge: {
    "送料込み（出品者負担)":0, "着払い（購入者負担)":1
  }

  enum delivery_days:{
    "1~2日で発送":0, "2~3日で発送":1, "4~7日で発送":2
  }

  enum item_statuses:{
    "新品、未使用":0, "目立った傷や汚れなし":1, "やや傷や汚れあり":2, "全体的に状態が悪い":3
  }
 
  belongs_to :category
  
  def self.items_search(search)
    if search
      Item.where(['name LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  def set_item
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def show
    @images = @item.images
    @children = Category.find(@item[:child_category_id])
    @grandchildren = Category.find(@item[:grandchild_category_id])
  end

  def new
    @item = Item.new
    @images = @item.images.build
    # Categoriesテーブルの上から13個のレコードを取り出す
    @parents = Category.all.order("id ASC").limit(13)
  end

  def create  
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
      
    else
      render  new_item_path
    end
  end
  
  def edit
    unless @item.user_id == current_user.id
      redirect_to  root_path
    end
    @parents = Category.all.order("id ASC").limit(13)
    @parent = Category.find(@item[:category_id])
    @children = @parent.children
    @grandchildren = @parent.indirects
  end
  
  def update
    if @item.update(item_update_params)
      redirect_to root_path
    else
      redirect_to  edit_item_path(@item.id)
    end
  end
  
  def search
    respond_to do |format|
      format.html
      format.json do
        @children = Category.find(params[:parent_id]).children
        #親ボックスのidから子ボックスのidの配列を作成してインスタンス変数で定義
      end
    end
  end
  
  def search_two
    respond_to do |format|
      format.html
      format.json do
        @grandchildren = Category.find(params[:child_id]).children
        #子ボックスのidから孫ボックスのidの配列を作成してインスタンス変数で定義
      end
    end
  end
  
  
  def buyscreen
  end
  
  def destroy
    if current_user.id == @item.user_id
      @item.destroy
      redirect_to root_path, notice: "商品が削除されました"     
    else
      redirect_to root_path, alert: "削除に失敗しました"
    end
  end
  
  def items_search
    @items = Item.items_search(params[:keyword])
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :description, :status, :price, :payer, :preday, :sold, :postage_type_id, :category_id,:child_category_id,:grandchild_category_id, :prefecture_id, images_attributes: [:image]).merge(user_id: current_user.id)
  end
  
  def item_update_params
    params.require(:item).permit(
      :name, :description, :status, :price, :payer, :preday, :sold, :postage_type_id, :category_id,:child_category_id,:grandchild_category_id, :prefecture_id,
      [images_attributes: [:image, :_destroy, :id]]).merge(user_id: current_user.id)
    end
    
    def set_item
      @item = Item.find(params[:id])
    end
  end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.haml
.main__pickup__productbox__lists__list
  -if item.saler_id.present? 
    .items-box_photo__sold
      .items-box_photo__sold__inner
        SOLD
  =link_to "items/#{item.id}" do
    = image_tag item.images[0].image.url, class: "productimage"
    .list__body
      %h3.name #{item.name}
      .datalist
        %ul
          %li #{item.price}円
          %li 
            =icon("fas","star")
            0
        %p (税込)

app/views/items/buyscreen.html.haml
.main1
  .main1__section
    %h2.buy-head 購入内容の確認
    .main1__section__inner
      .main1__section__inner__items
        .item-box
          %h3.item_image
            =image_tag "/image1.png"
          .item-box-data
            %p.item-name 仮りのアイテム
            %p.item-price 
              %span.money ¥4800
              %span.tax (税込)送料込み
    .main1__section__inner
      .main1__section__inner__items
        = form_with model: @item do |f|
          %ul.price-table
            %li.price-big
              .merge-price
                %span 支払い金額
              .buy-price
                %span ¥4,800
          .item-info
            .item-info-inner
              %h3 支払い方法
              -# カード情報を登録しているか、どうかでビューが変わる
              .links
                =icon("fas","star")
                =link_to "登録してください","#"
          .item-info
            .item-info-inner
              %h3 配送先
              -# 同じく住所を登録しているかどうかでビューが変わる
              .links
                =icon("fas","star")
                =link_to "登録してください","#"
          .item-info
            .item-info-button
              %button(type="submit") 購入する

app/views/items/edit.html.haml
.new-content 
  .new-item
    .new-item-content
      = form_with model: @item, local: true,class: "new_user", id: "new_user" do |f|
        .new-item-content__images
          .new-item-content__images__box
            .new-item-content__images__title
              商品画像
            .required
              必須
          .new-item-content__images__explanation
            最大5枚までアップロードできます
          .new-item-content__images__itemsbox
            .prev-content
              //JSで挿入したhtmlと同じ形 each文でのプレビュー表示
              - @item.images.each do |image|
                .preview-box
                  .upper-box
                    = image_tag image.image.url, width: "112", height: "112", alt: "preview"
                  .lower-box
                    .update-box
                      %label.edit-btn 編集
                    .delete-box
                      .delete-btn
                        %span 削除
            
            .label-content
            
              //プレビューの数に合わせてforオプションを指定
              = f.label :"images_attributes_#{@item.images.length}_image", class: "label-box", id: "label-box--#{@item.images.length}" do
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images do |i|

                //プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置
                = i.file_field :image, class: "hidden-field"
                = i.check_box:_destroy, class: "hidden-checkbox"

                //5つのfile_fieldを準備するに当たって、足りない分を表示
              - @item.images.length.upto(4) do |i|
                %input{name: "item[images_attributes][#{i}][image]", id: "item_images_attributes_#{i}_image", class:"hidden-field", type:"file"}

        .new-item-content__item
          .new-item-content__item__box
            .new-item-content__item__title
              商品名
            .required
              必須
          = f.text_field :name, placeholder: "40文字まで", class: 'new-item-content__item__name'
          .new-item-content__item__box
            .new-item-content__item__title
              商品説明
            .required
              必須
          = f.text_area :description, class: 'new-item-content__item__description', cols: "50", rows: "7", placeholder: "商品の説明（必須 1,000文字以内&#13;(色、素材、重さ、定価、注意点など）&#13;&#13;例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。".html_safe 
          .new-item-content__item__description__count
            0/1000
        .new-item-content__thedetails
          .new-item-content__thedetails__title
            商品の詳細
          .new-item-content__thedetails__box
            .new-item-content__item__box__title
              カテゴリー
            .required
              必須
          .new-item-content__thedetails__category
            = f.collection_select :category_id, @parents, :id, :name, { prompt: "---" }, { class: "category_select-box", id: "category_select" }
            .children_category
              = f.collection_select :child_category_id, @children, :id, :name, { prompt: "---" }, { class: "category_select-box", id: "child_category" }
            .grand_category
              = f.collection_select :grandchild_category_id, @grandchildren, :id, :name, { prompt: "---" }, { class: "category_select-box", id: "grandchild_category" }
          .new-item-content__thedetails__box
            .new-item-content__item__box__title
              商品の状態
            .required
              必須
          = f.select :status, Item.item_statuses, {prompt: "選択してください"}, {class: 'new-item-content__thedetails__status'}
        .new-item-content__delivery
          .new-item-content__delivery__title
            配送について
          .new-item-content__delivery__box
            .new-item-content__delivery__box__title
              配送料の負担
            .required
              必須
          = f.select :payer, Item.delivery_charges, {prompt: "選択してください"}, {class: 'new-item-content__delivery__payer'}
          .new-item-content__delivery__box
            .new-item-content__delivery__box__title
              発送元の地域
            .required
              必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください"
          .new-item-content__delivery__box
            .new-item-content__delivery__box__title
              発送までの日数
            .required
              必須
          = f.select :preday, Item.delivery_days, {prompt: "選択してください"}, {class: 'new-item-content__delivery__preday'}
        .new-item-content__price
          .new-item-content__price__title
            価格
          .new-item-content__price__flex
            .new-item-content__price__box
              .new-item-content__price__box__title
                販売価格
              .required
                必須
            .new-item-content__price__input
              .new-item-content__price__input__text
                ¥
              = f.text_field :price, placeholder: "0", class: 'new-item-content__price__input__form'
        .new-item-content__submit
          .new-item-content__submit__box
            = f.submit class: 'new-item-content__submit__box__submit-btn', value: '出品する'
            = link_to item_path(@item.id), class: "new-item-content__submit__box__return-btn" do
              もどる

app/views/items/index.html.haml
.main
  -# 人生を変えるフリマアプリバナー
  .main__visual
    .main__visual__content
      %h2.content__subtitle 人生を変えるフリマアプリ
      %p.content__text
        FURIMAは誰でも簡単に出品・購入できる
        %br
        フリマアプリです。
      .main__visual__content__btn
        = link_to image_tag(src= "/appstore.png", class: "abtn"), "#", class: "alink"
        = link_to image_tag(src= "/googleplay.png", class: "gbtn"), "#"
  
  -# FURIMAが選ばれる3つの理由
  .main__topintro
    %h2.subtitle FRIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .main__topintro__pict
          %span.number 1
          = image_tag "/select1.jpg", size: "250x290"
        %h3.list__text
          %span 3分
          ですぐに出品！
        %p.list__description スマホで入力するだけで簡単に出品できる！
      %li.list
        .main__topintro__pict
          %span.number 2
          = image_tag "/select2.jpg", size: "250x290"
        %h3.list__text
          %span シンプル
          で使いやすい！
        %p.list__description めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        .main__topintro__pict
          %span.number 3
          = image_tag "/select3.jpg", size: "250x290"
        %h3.list__text
          手数料
          %span 業界最安
        %p.list__description 最大3%でお得に出品&購入！

  -# 会員数日本一位バナー
  .main__middle
    .main__middle__content
      %h2.subtitle 会員数日本一位
      %p.text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .main__visual__content__btn
        = link_to image_tag(src= "/appstore.png", class: "abtn"), "#", class: "alink"
        = link_to image_tag(src= "/googleplay.png", class: "gbtn"), "#"
  
  -# FURIMAの特徴
  .main__charactor
    %h2.headtitle FURIMAの特徴
    %ul.lists2
      %li.list2
        .main__charactor__pict
          = image_tag "/man1.svg", size: "250x320"
        %h3.list2__text 簡単に売り買いできる
        %p.list2__description スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.list2
        .main__charactor__pict
          = image_tag "/man2.svg", size: "250x320"
        %h3.list2__text 売上金は即日振込みに対応
        %p.list2__description 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.list2
        .main__charactor__pict
          = image_tag "/man3.svg", size: "250x320"
        %h3.list2__text 様々な支払いに対応
        %p.list2__description お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  
  -# ピックアップカテゴリー
  .main__pickup
    %h2.head ピックアップカテゴリー
    .main__pickup__productbox
      .main__pickup__productbox__head
        %h3.title
          =link_to "新規投稿商品","#"
      .main__pickup__productbox__lists
        -# 商品情報を表示
        = render @items 

  -# ピックアップブランド
  .main__pickup
    %h2.head ピックアップブランド
    .main__pickup__productbox
      .main__pickup__productbox__head
        %h3.title
          =link_to "アーカイバ","#"
      .main__pickup__productbox__lists
        -# 商品情報を表示
        = render @items  

app/views/items/items_search.html.haml
.main__search
  - @items.each do |item|
    .search__content
      =link_to "#{item.id}" do
        = image_tag item.images[0].image.url, class: "productimage"
      .list__body
        %h3.name
          =link_to "#{item.id}" do
            = item.name
        .datelist
          %ul
            %li #{item.price}円
            %li 
              =icon("fas","star")
              0
          %p (税込)

app/views/items/new.html.haml
.new-content 
  .new-item
    .new-item-content
      = form_with model: @item, local: true,class: "new_user", id: "new_user" do |f|
        .new-item-content__images
          .new-item-content__images__box
            .new-item-content__images__title
              商品画像
            .required
              必須
          .new-item-content__images__explanation
            最大5枚までアップロードできます
          .new-item-content__images__itemsbox
            .prev-content
            .label-content
              %label{for: "item_images_attributes_0_image", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images do |i|
                = i.file_field :image, class: "hidden-field"
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][1][image]", id: "item_images_attributes_1_image" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][2][image]", id: "item_images_attributes_2_image" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][3][image]", id: "item_images_attributes_3_image" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][4][image]", id: "item_images_attributes_4_image" }
        .new-item-content__item
          .new-item-content__item__box
            .new-item-content__item__title
              商品名
            .required
              必須
          = f.text_field :name, placeholder: "40文字まで", class: 'new-item-content__item__name'
          .new-item-content__item__box
            .new-item-content__item__title
              商品説明
            .required
              必須
          = f.text_area :description, class: 'new-item-content__item__description', cols: "50", rows: "7", placeholder: "商品の説明（必須 1,000文字以内&#13;(色、素材、重さ、定価、注意点など）&#13;&#13;例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。".html_safe 
          .new-item-content__item__description__count
            0/1000
        .new-item-content__thedetails
          .new-item-content__thedetails__title
            商品の詳細
          .new-item-content__thedetails__box
            .new-item-content__item__box__title
              カテゴリー
            .required
              必須
          .new-item-content__thedetails__category
            = f.collection_select :category_id, @parents, :id, :name, { prompt: "---" }, { class: "category_select-box", id: "category_select" }
          .new-item-content__thedetails__box
            .new-item-content__item__box__title
              商品の状態
            .required
              必須
          = f.select :status, Item.item_statuses, {prompt: "選択してください"}, {class: 'new-item-content__thedetails__status'}
        .new-item-content__delivery
          .new-item-content__delivery__title
            配送について
          .new-item-content__delivery__box
            .new-item-content__delivery__box__title
              配送料の負担
            .required
              必須
          = f.select :payer, Item.delivery_charges, {prompt: "選択してください"}, {class: 'new-item-content__delivery__payer'}
          .new-item-content__delivery__box
            .new-item-content__delivery__box__title
              発送元の地域
            .required
              必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください"
          .new-item-content__delivery__box
            .new-item-content__delivery__box__title
              発送までの日数
            .required
              必須
          = f.select :preday, Item.delivery_days, {prompt: "選択してください"}, {class: 'new-item-content__delivery__preday'}
        .new-item-content__price
          .new-item-content__price__title
            価格
          .new-item-content__price__flex
            .new-item-content__price__box
              .new-item-content__price__box__title
                販売価格
              .required
                必須
            .new-item-content__price__input
              .new-item-content__price__input__text
                ¥
              = f.text_field :price, placeholder: "0", class: 'new-item-content__price__input__form'
        .new-item-content__submit
          .new-item-content__submit__box
            = f.submit class: 'new-item-content__submit__box__submit-btn', value: '出品する'
            = link_to "#", class: "new-item-content__submit__box__return-btn" do
              もどる

app/views/items/show.html.haml
.main2
  .main2__show
    .main2__show__content
      .main2__show__content__top
        .itemsbox
          %h2.itemsbox__name
            = @item.name
          .itemsbox__body
            %ul.imagebox
              %li.images
                -if @item.saler_id.present? 
                  .items-box_photo__sold
                    .items-box_photo__sold__inner
                      SOLD
                =image_tag @item.images[0].image.url, class:"big_image"
                %ul
                  - @images.each do |image|
                    %li
                      = image_tag image.image.url, class:"mini_image"
          .itemsbox__price
            %span.money
              ¥
              = @item.price
            .itemsbox__price__data
              %span （税込み）
              %span 送料込み
          .itemsbox__explan
            %p
              = @item.description
          .itemsbox__table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = @item.user.nickname
                %tr
                  %th カテゴリー
                  %td
                    = link_to @item.category.name,category_path(@item.category_id),method: :get
                    %br
                    = link_to @children.name,category_path(@item.child_category_id),method: :get
                    %br
                    =link_to @grandchildren.name,category_path(@item.grandchild_category_id),method: :get
                %tr
                  %th 商品の状態
                  %td
                    = Item.item_statuses.keys.to_a[@item.status]
                %tr
                  %th 配送料の負担
                  %td
                    = Item.delivery_charges.keys.to_a[@item.payer]
                %tr
                  %th 発送元の地域
                  %td
                    = @item.prefecture.name
                %tr
                  %th 発送日の目安
                  %td
                    = Item.delivery_days.keys.to_a[@item.preday]
         
          - if user_signed_in? && current_user.id != @item.user_id 
            -if @item.saler_id.present?
              .soldout
                売り切れました
            -else
              %button.buybutton(type="submit")
                = link_to "購入する",item_purchase_index_path(@item.id), method: :get
        .comments
          = form_with model: @comment do |f| 
            %textarea{name: "text"}
            %p.action
              相手のことを考えて丁寧にコメントしよう
              %br
              不快な言葉遣いはダメ絶対！
            %button.comebutton(type="submit")
              コメントする
        .main2__content__bottom
          = link_to @item.category.name+"をもっと見る",category_path(@item.category_id)
        - if user_signed_in? && current_user.id == @item.user_id 
          .edititem
            = link_to "商品の編集",edit_item_path(@item.id), method: :get
        
          .destroyitem
            = link_to "この商品を削除する",item_path(@item.id), method: :delete

-# = link_to @item.category.name,category_path(@item.category_id),method: :get