config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:edit, :update, :show]
  root 'items#index'
    resources :address, only: [:create,:edit, :update]
  
    resources :card, only: [:new, :show] do
      collection do
        post 'show', to: 'card#show'
        post 'pay', to: 'card#pay'
        post 'delete', to: 'card#delete'
      end
    end

    resources :items  do
      resources :purchase, only: [:index] do
        collection do
          get 'index', to: 'purchase#index'
          post 'pay', to: 'purchase#pay'
          get 'done', to: 'purchase#done'
        end
      end
      collection do
        get :search
        get :search_two
        get :items_search
      end
    end
  resources :categories, only: [:new, :show]
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  before_action :set_card, only: [:show, :delete]


  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    unless @card.blank?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
.new-card-content
  -# 支払い方法
  .new-card
    .new-card__title
      支払い方法
    .new-card__content
      = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        -#  カード番号
        .new-card__content__card-number
          .new-card__content__card-number__box
            %label カード番号
            .required
              必須
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number", name: "card-number"
        %br
        -# 有効期限
        .new-card__content__card-date
          .new-card__content__card-date__box
            %label 有効期限
            .required
              必須
          .new-card__content__card-date__box2
            %select#exp_month{name: "exp_month", type: "text", class: "exp_month"}
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span.exp_month__text 月
            %select#exp_year{name: "exp_year", type: "text", class: "exp_year"}
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span.exp_year__text 年
        %br
        -# セキュリティーコード
        .new-card__content__card-security
          .new-card__content__card-security__box
            %label セキュリティコード
            .required
              必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc", name: "cvc-number"
        %br
        -# 登録ボタン
        #card_token
        = submit_tag "登録する", id: "token_submit"

app/views/card/show.html.haml
.register-card-content
  -# クレジットカード情報
  .register-card-item
    .register-card-item__title 
      クレジットカード情報
    %br
    -# カード番号
    .register-card-item__card-number
      = "**** **** **** " + @default_card_information.last4
    %br
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    -# 有効期限
    .register-card-item__date
      %p 有効期限
      = exp_month + " / " + exp_year
    %br
    -# 削除ボタン
    = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %input{ type: "hidden", name: "card_id", value: "" }
      %button.register-card-item__submit 削除する