config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:edit, :update, :show]
  root 'items#index'
    resources :address, only: [:create,:edit, :update]
  
    resources :card, only: [:new, :show] do
      collection do
        post 'show', to: 'card#show'
        post 'pay', to: 'card#pay'
        post 'delete', to: 'card#delete'
      end
    end

    resources :items  do
      resources :purchase, only: [:index] do
        collection do
          get 'index', to: 'purchase#index'
          post 'pay', to: 'purchase#pay'
          get 'done', to: 'purchase#done'
        end
      end
      collection do
        get :search
        get :search_two
        get :items_search
      end
    end
  resources :categories, only: [:new, :show]
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample76b
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    -# フラッシュ情報
    .notifications
      - flash.each do |key, value|
        = content_tag(:div, value, class: key)
  
    .header
      .header__inner
        .header__inner__mainheader
          = link_to image_tag(src= "/logo2.png", class: "homebtn"), "/"
          .header__inner__mainheader__searchbox
            = form_with(url: items_search_items_path, method: :get, local:true) do |form|
              = form.text_field :keyword, class: 'inputbox__text', placeholder: 'キーワード検索'
              %button(type="submit")
                =icon("fas","search")

                
        .header__inner__nav
          %ul.listsleft
            %li.listsleft__item
              .catbtn
                カテゴリー
                .category_box
                  .parents_box
                    - @parents.each do |parent|
                      = link_to "#{parent.name}", "/categories/#{parent.id}", class: "parent_category",id: "#{parent.id}"
                  .children_box
                  .grand_children_box

            %li.listsleft__item2
              =link_to "ブランド", "#", class:"brandbtn"

          %ul.listsright
            -if user_signed_in?        
              = link_to user_path(current_user.id), method: :get,class:"listsright__item" do
                %li マイページ< #{current_user.nickname}
              = link_to destroy_user_session_path, method: :delete, class:"listsright__item" do
                %li ログアウト
            - else
              = link_to user_session_path, method: :post,class:"listsright__item" do
                %li ログイン
              = link_to  "/users/sign_up", method: :get,class:"listsright__item" do
                %li 新規会員登録

    = yield
    
    .appbanner
      .appbanner__inner
        %h2.banner__subtitle 誰でも簡単フリマアプリ
        %p.banner__text 今すぐ無料ダウンロード
        .appbanner__inner__icon
          = link_to image_tag(src= "/appstore.png", class: "abtn"), "#", class: "alink"
          = link_to image_tag(src= "/googleplay.png", class: "gbtn"), "#"
    
    .footer
      %ul.contents
        %li.content
          %h2.content__head FURIMAについて
          %ul
            %li
              =link_to "会社概要（運営会社）", "#"
            %li
              =link_to "プライバシーポリシー", "#"
            %li
              =link_to "FURIMA利用規約", "#"
            %li
              =link_to "ポイントに関する特約", "#"
        %li.content
          %h2.content__head FURIMAを見る
          %ul
            %li
              =link_to "カテゴリー一覧", "#"
            %li
              =link_to "ブランド一覧", "#"
        %li.content
          %h2.content__head ヘルプ&ガイド
          %ul
            %li
              =link_to "FURIMAガイド", "#"
            %li
              =link_to "FURIMAロゴ利用ガイドライン", "#"
            %li
              =link_to "お知らせ", "#"
      .footer__logo
        = link_to image_tag(src= "/logo2.svg", class: "footerlogo"), "#"
      %p ©️ FURIMA
    
    .purchasbtn
      = link_to image_tag(src= "/syupin1.png", class: "syupin"), new_item_path